/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Kiểm tra xem server có đang chạy không
         */
        get: operations["getIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ws/device/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ws/client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng ký tài khoản mới
         * @description Tạo tài khoản người dùng mới với email, tên người dùng và mật khẩu. Một email xác minh sẽ được gửi.
         */
        post: operations["postApiAuthRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Xác minh email
         * @description Xác minh địa chỉ email người dùng bằng token được gửi trong email. Trả về JWT token khi thành công.
         */
        get: operations["getApiAuthVerify-email"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng nhập
         * @description Đăng nhập bằng email và mật khẩu. Trả về JWT token nếu thành công.
         */
        post: operations["postApiAuthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postApiAuthLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tạo URL upload MinIO
         * @description Trả về presigned URL để upload ảnh lên MinIO/S3
         */
        post: operations["postApiPostsUpload-url"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Danh sách bài viết
         * @description Liệt kê các bài viết mới nhất kèm media và chỉ số AQI.
         */
        get: operations["getApiPosts"];
        put?: never;
        /**
         * Tạo bài viết với AQI từ userInfo
         * @description Tạo bài viết mới, AQI sẽ được lấy tự động từ dữ liệu mới nhất của device (userInfo). Nếu có aqiIndex trong body sẽ dùng giá trị đó.
         */
        post: operations["postApiPosts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/trending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Danh sách bài viết nổi bật
         * @description Liệt kê các bài viết nổi bật dựa trên số phiếu upvote và downvote, kèm media và chỉ số AQI.
         */
        get: operations["getApiPostsTrending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chi tiết bài viết
         * @description Trả về thông tin bài viết kèm media và chỉ số AQI.
         */
        get: operations["getApiPostsById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upvote/Downvote bài viết
         * @description Tạo hoặc cập nhật phiếu bầu (up/down) cho bài viết.
         */
        post: operations["postApiPostsByIdVote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shop/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách sản phẩm */
        get: operations["getApiShopProducts"];
        put?: never;
        /**
         * Tạo sản phẩm mới (Admin only)
         * @description Tạo sản phẩm mới với ảnh và categories
         */
        post: operations["postApiShopProducts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shop/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chi tiết sản phẩm */
        get: operations["getApiShopProductsById"];
        put?: never;
        post?: never;
        /**
         * Xóa sản phẩm (Admin only)
         * @description Xóa sản phẩm và các categories liên quan
         */
        delete: operations["deleteApiShopProductsById"];
        options?: never;
        head?: never;
        /**
         * Cập nhật sản phẩm (Admin only)
         * @description Cập nhật thông tin sản phẩm bao gồm ảnh và categories
         */
        patch: operations["patchApiShopProductsById"];
        trace?: never;
    };
    "/api/shop/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách danh mục */
        get: operations["getApiShopCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shop/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Đơn hàng của tôi (Authenticated users)
         * @description Lấy danh sách đơn hàng của user đã đăng nhập
         */
        get: operations["getApiShopOrders"];
        put?: never;
        /**
         * Tạo đơn hàng (Guest hoặc User đã đăng nhập)
         * @description Guest cần cung cấp customerName, customerEmail, customerPhone, shippingAddress. User đã đăng nhập không cần.
         */
        post: operations["postApiShopOrders"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shop/orders/track/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tra cứu đơn hàng bằng ID và email (cho Guest)
         * @description Guest users có thể tra cứu đơn hàng bằng ID và email đã dùng khi đặt hàng
         */
        get: operations["getApiShopOrdersTrackById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shop/products/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tạo URL upload ảnh sản phẩm (Admin only)
         * @description Trả về presigned URL để upload ảnh sản phẩm lên MinIO/S3
         */
        post: operations["postApiShopProductsUpload-url"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shop/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chi tiết đơn hàng (Authenticated users)
         * @description Xem chi tiết đơn hàng của chính mình
         */
        get: operations["getApiShopOrdersById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shop/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tạo đánh giá sản phẩm */
        post: operations["postApiShopReviews"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shop/products/{id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách đánh giá sản phẩm */
        get: operations["getApiShopProductsByIdReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/esp32/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Device đăng nhập
         * @description Đăng nhập và đăng ký IoT device để gửi dữ liệu AQI
         */
        post: operations["postApiEsp32Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/esp32/aqi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gửi dữ liệu AQI
         * @description Device gửi chỉ số AQI hiện tại để lưu vào profile user
         */
        post: operations["postApiEsp32Aqi"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/esp32/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Heartbeat / Keep-alive
         * @description ESP32 gửi heartbeat để cập nhật lastSeen
         */
        post: operations["postApiEsp32Heartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/esp32/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng xuất device
         * @description Vô hiệu hóa device registration
         */
        post: operations["postApiEsp32Logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thống kê hệ thống */
        get: operations["getApiAdminStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách users */
        get: operations["getApiAdminUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chi tiết user */
        get: operations["getApiAdminUsersById"];
        put?: never;
        post?: never;
        /** Xóa user */
        delete: operations["deleteApiAdminUsersById"];
        options?: never;
        head?: never;
        /** Cập nhật user */
        patch: operations["patchApiAdminUsersById"];
        trace?: never;
    };
    "/api/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách sản phẩm */
        get: operations["getApiAdminProducts"];
        put?: never;
        /** Tạo sản phẩm */
        post: operations["postApiAdminProducts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Xóa sản phẩm */
        delete: operations["deleteApiAdminProductsById"];
        options?: never;
        head?: never;
        /** Cập nhật sản phẩm */
        patch: operations["patchApiAdminProductsById"];
        trace?: never;
    };
    "/api/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách đơn hàng */
        get: operations["getApiAdminOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Xóa đơn hàng */
        delete: operations["deleteApiAdminOrdersById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách IoT devices */
        get: operations["getApiAdminDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Xóa device */
        delete: operations["deleteApiAdminDevicesById"];
        options?: never;
        head?: never;
        /** Vô hiệu hóa device */
        patch: operations["patchApiAdminDevicesById"];
        trace?: never;
    };
    "/api/admin/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách bài viết */
        get: operations["getApiAdminPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Xóa bài viết */
        delete: operations["deleteApiAdminPostsById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/check/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kiểm tra device đã có user hay chưa
         * @description Kiểm tra xem một device đã kết nối với user nào hay chưa. Endpoint này không yêu cầu authorization vì dùng cho phần cứng.
         */
        get: operations["getApiDevicesCheckByDeviceId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lấy danh sách thiết bị của user
         * @description Trả về tất cả thiết bị IoT thuộc về user hiện tại
         */
        get: operations["getApiDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lấy thông tin chi tiết thiết bị
         * @description Trả về thông tin chi tiết của một thiết bị theo deviceId
         */
        get: operations["getApiDevicesByDeviceId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload user avatar
         * @description Upload user avatar directly to MinIO/S3. Max 5MB. Supported: PNG, JPG, GIF, WebP
         */
        post: operations["postApiUserAvatar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lấy thông tin user hiện tại
         * @description Lấy thông tin của user hiện tại kèm AQI, PPM và user info. Yêu cầu xác thực bằng token JWT.
         */
        get: operations["getApiUserMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Cập nhật thông tin user hiện tại
         * @description Cập nhật thông tin user (username, email, avatar, firstName, lastName, phoneNumber, age). Yêu cầu xác thực bằng token JWT.
         */
        patch: operations["patchApiUserMe"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    postApiAuthRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Tên người dùng */
                    username: string;
                    /**
                     * Format: email
                     * @description Địa chỉ email
                     */
                    email: string;
                    /** @description Mật khẩu (tối thiểu 6 ký tự) */
                    password: string;
                    /** @description Xác nhận mật khẩu */
                    confirmPassword: string;
                    /** @description ID thiết bị IoT (nếu có) */
                    deviceId?: string;
                };
                "application/x-www-form-urlencoded": {
                    /** @description Tên người dùng */
                    username: string;
                    /**
                     * Format: email
                     * @description Địa chỉ email
                     */
                    email: string;
                    /** @description Mật khẩu (tối thiểu 6 ký tự) */
                    password: string;
                    /** @description Xác nhận mật khẩu */
                    confirmPassword: string;
                    /** @description ID thiết bị IoT (nếu có) */
                    deviceId?: string;
                };
                "multipart/form-data": {
                    /** @description Tên người dùng */
                    username: string;
                    /**
                     * Format: email
                     * @description Địa chỉ email
                     */
                    email: string;
                    /** @description Mật khẩu (tối thiểu 6 ký tự) */
                    password: string;
                    /** @description Xác nhận mật khẩu */
                    confirmPassword: string;
                    /** @description ID thiết bị IoT (nếu có) */
                    deviceId?: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message?: string;
                        token?: string;
                    };
                };
            };
            /** @description Response for status 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    "getApiAuthVerify-email": {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message?: string;
                        token?: string;
                    };
                };
            };
            /** @description Response for status 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    postApiAuthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @description Địa chỉ email
                     */
                    email: string;
                    /** @description Mật khẩu */
                    password: string;
                };
                "application/x-www-form-urlencoded": {
                    /**
                     * Format: email
                     * @description Địa chỉ email
                     */
                    email: string;
                    /** @description Mật khẩu */
                    password: string;
                };
                "multipart/form-data": {
                    /**
                     * Format: email
                     * @description Địa chỉ email
                     */
                    email: string;
                    /** @description Mật khẩu */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message?: string;
                        token?: string;
                    };
                };
            };
            /** @description Response for status 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                    };
                };
            };
        };
    };
    postApiAuthLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    "postApiPostsUpload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description MIME type, vd: image/png */
                    contentType: string;
                    /** @description Phần mở rộng file, vd: png */
                    extension?: string;
                };
                "application/x-www-form-urlencoded": {
                    /** @description MIME type, vd: image/png */
                    contentType: string;
                    /** @description Phần mở rộng file, vd: png */
                    extension?: string;
                };
                "multipart/form-data": {
                    /** @description MIME type, vd: image/png */
                    contentType: string;
                    /** @description Phần mở rộng file, vd: png */
                    extension?: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        uploadUrl: string;
                        key: string;
                        url: string;
                    };
                };
            };
        };
    };
    getApiPosts: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: string;
                            userId: string;
                            author: {
                                id: string;
                                username: string;
                                avatarUrl?: string;
                            };
                            title: string;
                            content: string;
                            aqiIndex: number;
                            location: {
                                /** @description Vĩ độ */
                                lat: number;
                                /** @description Kinh độ */
                                lng: number;
                                /** @description Tên địa điểm */
                                name?: string;
                            };
                            upVotes: number;
                            downVotes: number;
                            createdAt: string;
                            updatedAt: string;
                            media: {
                                /** @description Object key trên S3/MinIO */
                                key: string;
                                /** @description Public URL của file */
                                url: string;
                                contentType?: string;
                                size?: number;
                                width?: number;
                                height?: number;
                            }[];
                        }[];
                        total: number;
                    };
                };
            };
        };
    };
    postApiPosts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                    content: string;
                    aqiIndex?: number;
                    location: {
                        /** @description Vĩ độ */
                        lat: number;
                        /** @description Kinh độ */
                        lng: number;
                        /** @description Tên địa điểm */
                        name?: string;
                    };
                    media?: {
                        /** @description Object key trên S3/MinIO */
                        key: string;
                        /** @description Public URL của file */
                        url: string;
                        contentType?: string;
                        size?: number;
                        width?: number;
                        height?: number;
                    }[];
                };
                "application/x-www-form-urlencoded": {
                    title: string;
                    content: string;
                    aqiIndex?: number;
                    location: {
                        /** @description Vĩ độ */
                        lat: number;
                        /** @description Kinh độ */
                        lng: number;
                        /** @description Tên địa điểm */
                        name?: string;
                    };
                    media?: {
                        /** @description Object key trên S3/MinIO */
                        key: string;
                        /** @description Public URL của file */
                        url: string;
                        contentType?: string;
                        size?: number;
                        width?: number;
                        height?: number;
                    }[];
                };
                "multipart/form-data": {
                    title: string;
                    content: string;
                    aqiIndex?: number;
                    location: {
                        /** @description Vĩ độ */
                        lat: number;
                        /** @description Kinh độ */
                        lng: number;
                        /** @description Tên địa điểm */
                        name?: string;
                    };
                    media?: {
                        /** @description Object key trên S3/MinIO */
                        key: string;
                        /** @description Public URL của file */
                        url: string;
                        contentType?: string;
                        size?: number;
                        width?: number;
                        height?: number;
                    }[];
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        userId: string;
                        author: {
                            id: string;
                            username: string;
                            avatarUrl?: string;
                        };
                        title: string;
                        content: string;
                        aqiIndex: number;
                        location: {
                            /** @description Vĩ độ */
                            lat: number;
                            /** @description Kinh độ */
                            lng: number;
                            /** @description Tên địa điểm */
                            name?: string;
                        };
                        upVotes: number;
                        downVotes: number;
                        createdAt: string;
                        updatedAt: string;
                        media: {
                            /** @description Object key trên S3/MinIO */
                            key: string;
                            /** @description Public URL của file */
                            url: string;
                            contentType?: string;
                            size?: number;
                            width?: number;
                            height?: number;
                        }[];
                    };
                };
            };
        };
    };
    getApiPostsTrending: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: string;
                            userId: string;
                            author: {
                                id: string;
                                username: string;
                                avatarUrl?: string;
                            };
                            title: string;
                            content: string;
                            aqiIndex: number;
                            location: {
                                /** @description Vĩ độ */
                                lat: number;
                                /** @description Kinh độ */
                                lng: number;
                                /** @description Tên địa điểm */
                                name?: string;
                            };
                            upVotes: number;
                            downVotes: number;
                            createdAt: string;
                            updatedAt: string;
                            media: {
                                /** @description Object key trên S3/MinIO */
                                key: string;
                                /** @description Public URL của file */
                                url: string;
                                contentType?: string;
                                size?: number;
                                width?: number;
                                height?: number;
                            }[];
                        }[];
                        total: number;
                    };
                };
            };
        };
    };
    getApiPostsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        userId: string;
                        author: {
                            id: string;
                            username: string;
                            avatarUrl?: string;
                        };
                        title: string;
                        content: string;
                        aqiIndex: number;
                        location: {
                            /** @description Vĩ độ */
                            lat: number;
                            /** @description Kinh độ */
                            lng: number;
                            /** @description Tên địa điểm */
                            name?: string;
                        };
                        upVotes: number;
                        downVotes: number;
                        createdAt: string;
                        updatedAt: string;
                        media: {
                            /** @description Object key trên S3/MinIO */
                            key: string;
                            /** @description Public URL của file */
                            url: string;
                            contentType?: string;
                            size?: number;
                            width?: number;
                            height?: number;
                        }[];
                    };
                };
            };
        };
    };
    postApiPostsByIdVote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    value: 1 | -1;
                };
                "application/x-www-form-urlencoded": {
                    /** @enum {string} */
                    value: 1 | -1;
                };
                "multipart/form-data": {
                    /** @enum {string} */
                    value: 1 | -1;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        userId: string;
                        author: {
                            id: string;
                            username: string;
                            avatarUrl?: string;
                        };
                        title: string;
                        content: string;
                        aqiIndex: number;
                        location: {
                            /** @description Vĩ độ */
                            lat: number;
                            /** @description Kinh độ */
                            lng: number;
                            /** @description Tên địa điểm */
                            name?: string;
                        };
                        upVotes: number;
                        downVotes: number;
                        createdAt: string;
                        updatedAt: string;
                        media: {
                            /** @description Object key trên S3/MinIO */
                            key: string;
                            /** @description Public URL của file */
                            url: string;
                            contentType?: string;
                            size?: number;
                            width?: number;
                            height?: number;
                        }[];
                    };
                };
            };
        };
    };
    getApiShopProducts: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: string;
                            name: string;
                            description: string;
                            price: number;
                            stock: number;
                            imageUrl: string | null;
                            categories: {
                                id: string;
                                name: string;
                            }[];
                        }[];
                        total: number;
                    };
                };
            };
        };
    };
    postApiShopProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    description: string;
                    price: number;
                    stock: number;
                    imageUrl?: string;
                    categoryIds?: string[];
                };
                "application/x-www-form-urlencoded": {
                    name: string;
                    description: string;
                    price: number;
                    stock: number;
                    imageUrl?: string;
                    categoryIds?: string[];
                };
                "multipart/form-data": {
                    name: string;
                    description: string;
                    price: number;
                    stock: number;
                    imageUrl?: string;
                    categoryIds?: string[];
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        description: string;
                        price: number;
                        stock: number;
                        imageUrl: string | null;
                        categories: {
                            id: string;
                            name: string;
                        }[];
                    };
                };
            };
        };
    };
    getApiShopProductsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        description: string;
                        price: number;
                        stock: number;
                        imageUrl: string | null;
                        categories: {
                            id: string;
                            name: string;
                        }[];
                    };
                };
            };
        };
    };
    deleteApiShopProductsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        message: string;
                    };
                };
            };
        };
    };
    patchApiShopProductsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    description?: string;
                    price?: number;
                    stock?: number;
                    imageUrl?: string;
                    categoryIds?: string[];
                };
                "application/x-www-form-urlencoded": {
                    name?: string;
                    description?: string;
                    price?: number;
                    stock?: number;
                    imageUrl?: string;
                    categoryIds?: string[];
                };
                "multipart/form-data": {
                    name?: string;
                    description?: string;
                    price?: number;
                    stock?: number;
                    imageUrl?: string;
                    categoryIds?: string[];
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        description: string;
                        price: number;
                        stock: number;
                        imageUrl: string | null;
                        categories: {
                            id: string;
                            name: string;
                        }[];
                    };
                };
            };
        };
    };
    getApiShopCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: string;
                            name: string;
                            description: string;
                        }[];
                    };
                };
            };
        };
    };
    getApiShopOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: string;
                            userId?: string;
                            productId: string;
                            quantity: number;
                            totalPrice: number;
                            orderStatus: string;
                            customerName?: string;
                            customerEmail?: string;
                            customerPhone?: string;
                            shippingAddress?: string;
                            orderDate: string;
                        }[];
                    };
                };
            };
        };
    };
    postApiShopOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    productId: string;
                    quantity: number;
                    customerName?: string;
                    /** Format: email */
                    customerEmail?: string;
                    customerPhone?: string;
                    shippingAddress?: string;
                };
                "application/x-www-form-urlencoded": {
                    productId: string;
                    quantity: number;
                    customerName?: string;
                    /** Format: email */
                    customerEmail?: string;
                    customerPhone?: string;
                    shippingAddress?: string;
                };
                "multipart/form-data": {
                    productId: string;
                    quantity: number;
                    customerName?: string;
                    /** Format: email */
                    customerEmail?: string;
                    customerPhone?: string;
                    shippingAddress?: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        userId?: string;
                        productId: string;
                        quantity: number;
                        totalPrice: number;
                        orderStatus: string;
                        customerName?: string;
                        customerEmail?: string;
                        customerPhone?: string;
                        shippingAddress?: string;
                        orderDate: string;
                    };
                };
            };
        };
    };
    getApiShopOrdersTrackById: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        userId?: string;
                        productId: string;
                        quantity: number;
                        totalPrice: number;
                        orderStatus: string;
                        customerName?: string;
                        customerEmail?: string;
                        customerPhone?: string;
                        shippingAddress?: string;
                        orderDate: string;
                    };
                };
            };
        };
    };
    "postApiShopProductsUpload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description MIME type, e.g.: image/png */
                    contentType: string;
                    /** @description File extension, e.g.: png */
                    extension?: string;
                };
                "application/x-www-form-urlencoded": {
                    /** @description MIME type, e.g.: image/png */
                    contentType: string;
                    /** @description File extension, e.g.: png */
                    extension?: string;
                };
                "multipart/form-data": {
                    /** @description MIME type, e.g.: image/png */
                    contentType: string;
                    /** @description File extension, e.g.: png */
                    extension?: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        uploadUrl: string;
                        key: string;
                        url: string;
                    };
                };
            };
        };
    };
    getApiShopOrdersById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        userId?: string;
                        productId: string;
                        quantity: number;
                        totalPrice: number;
                        orderStatus: string;
                        customerName?: string;
                        customerEmail?: string;
                        customerPhone?: string;
                        shippingAddress?: string;
                        orderDate: string;
                    };
                };
            };
        };
    };
    postApiShopReviews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    productId: string;
                    rating: number;
                    comment: string;
                };
                "application/x-www-form-urlencoded": {
                    productId: string;
                    rating: number;
                    comment: string;
                };
                "multipart/form-data": {
                    productId: string;
                    rating: number;
                    comment: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        userId: string;
                        productId: string;
                        rating: number;
                        comment: string;
                        reviewDate: string;
                    };
                };
            };
        };
    };
    getApiShopProductsByIdReviews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: string;
                            userId: string;
                            productId: string;
                            rating: number;
                            comment: string;
                            reviewDate: string;
                        }[];
                    };
                };
            };
        };
    };
    postApiEsp32Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    /** @description ID duy nhất của device (MAC address, serial, v.v.) */
                    deviceId: string;
                    /** @description Tên thiết bị */
                    deviceName?: string;
                };
                "application/x-www-form-urlencoded": {
                    /** Format: email */
                    email: string;
                    password: string;
                    /** @description ID duy nhất của device (MAC address, serial, v.v.) */
                    deviceId: string;
                    /** @description Tên thiết bị */
                    deviceName?: string;
                };
                "multipart/form-data": {
                    /** Format: email */
                    email: string;
                    password: string;
                    /** @description ID duy nhất của device (MAC address, serial, v.v.) */
                    deviceId: string;
                    /** @description Tên thiết bị */
                    deviceName?: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description JWT token cho device sử dụng trong requests */
                        token: string;
                        /** @description ID của device registration */
                        registrationId: string;
                        expiresIn: string;
                    };
                };
            };
        };
    };
    postApiEsp32Aqi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Chỉ số AQI (0-500) */
                    aqi: number;
                    /** @description Unix timestamp (ms), mặc định là hiện tại */
                    timestamp?: number;
                };
                "application/x-www-form-urlencoded": {
                    /** @description Chỉ số AQI (0-500) */
                    aqi: number;
                    /** @description Unix timestamp (ms), mặc định là hiện tại */
                    timestamp?: number;
                };
                "multipart/form-data": {
                    /** @description Chỉ số AQI (0-500) */
                    aqi: number;
                    /** @description Unix timestamp (ms), mặc định là hiện tại */
                    timestamp?: number;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                        currentAQI: number;
                        lastUpdate: string;
                    };
                };
            };
        };
    };
    postApiEsp32Heartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                    };
                };
            };
        };
    };
    postApiEsp32Logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                    };
                };
            };
        };
    };
    getApiAdminStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        totalUsers: number;
                        totalProducts: number;
                        totalOrders: number;
                        totalDevices: number;
                        totalPosts: number;
                        activeDevices: number;
                    };
                };
            };
        };
    };
    getApiAdminUsers: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: string;
                            username: string;
                            email: string;
                            verified: number;
                            role: string;
                            currentAQI: number;
                            createdAt?: string;
                        }[];
                        total: number;
                    };
                };
            };
        };
    };
    getApiAdminUsersById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        username: string;
                        email: string;
                        verified: number;
                        role: string;
                        currentAQI: number;
                        createdAt?: string;
                    };
                };
            };
        };
    };
    deleteApiAdminUsersById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                    };
                };
            };
        };
    };
    patchApiAdminUsersById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    role?: string;
                    verified?: number;
                };
                "application/x-www-form-urlencoded": {
                    role?: string;
                    verified?: number;
                };
                "multipart/form-data": {
                    role?: string;
                    verified?: number;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        username: string;
                        email: string;
                        verified: number;
                        role: string;
                        currentAQI: number;
                        createdAt?: string;
                    };
                };
            };
        };
    };
    getApiAdminProducts: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: string;
                            name: string;
                            description: string;
                            price: number;
                            stock: number;
                        }[];
                        total: number;
                    };
                };
            };
        };
    };
    postApiAdminProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    description: string;
                    price: number;
                    stock: number;
                };
                "application/x-www-form-urlencoded": {
                    name: string;
                    description: string;
                    price: number;
                    stock: number;
                };
                "multipart/form-data": {
                    name: string;
                    description: string;
                    price: number;
                    stock: number;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        description: string;
                        price: number;
                        stock: number;
                    };
                };
            };
        };
    };
    deleteApiAdminProductsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                    };
                };
            };
        };
    };
    patchApiAdminProductsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    description?: string;
                    price?: number;
                    stock?: number;
                };
                "application/x-www-form-urlencoded": {
                    name?: string;
                    description?: string;
                    price?: number;
                    stock?: number;
                };
                "multipart/form-data": {
                    name?: string;
                    description?: string;
                    price?: number;
                    stock?: number;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        description: string;
                        price: number;
                        stock: number;
                    };
                };
            };
        };
    };
    getApiAdminOrders: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: string;
                            userId: string;
                            productId: string;
                            quantity: number;
                            orderDate: string;
                        }[];
                        total: number;
                    };
                };
            };
        };
    };
    deleteApiAdminOrdersById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                    };
                };
            };
        };
    };
    getApiAdminDevices: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: string;
                            userId: string;
                            deviceId: string;
                            deviceName: string;
                            deviceType: string;
                            isActive: number;
                            lastSeen?: string;
                            createdAt: string;
                        }[];
                        total: number;
                    };
                };
            };
        };
    };
    deleteApiAdminDevicesById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                    };
                };
            };
        };
    };
    patchApiAdminDevicesById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        userId: string;
                        deviceId: string;
                        deviceName: string;
                        deviceType: string;
                        isActive: number;
                        lastSeen?: string;
                        createdAt: string;
                    };
                };
            };
        };
    };
    getApiAdminPosts: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            id: string;
                            userId: string;
                            title: string;
                            aqiIndex: number;
                            upVotes: number;
                            downVotes: number;
                            createdAt: string;
                        }[];
                        total: number;
                    };
                };
            };
        };
    };
    deleteApiAdminPostsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                    };
                };
            };
        };
    };
    getApiDevicesCheckByDeviceId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        hasUser: boolean;
                        userId?: string;
                        deviceId: string;
                        deviceName?: string;
                        isActive?: number;
                    };
                };
            };
        };
    };
    getApiDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        devices: {
                            id: string;
                            deviceId: string;
                            deviceName?: string;
                            deviceType?: string;
                            isActive: number;
                            lastSeen?: string;
                            createdAt: string;
                        }[];
                        total: number;
                    };
                };
            };
        };
    };
    getApiDevicesByDeviceId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        deviceId: string;
                        deviceName?: string;
                        deviceType?: string;
                        isActive: number;
                        lastSeen?: string;
                        createdAt: string;
                    };
                };
            };
        };
    };
    postApiUserAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: binary
                     * @description Avatar image file (PNG, JPG, GIF, WebP)
                     * @default File
                     */
                    file: string;
                };
                "application/x-www-form-urlencoded": {
                    /**
                     * Format: binary
                     * @description Avatar image file (PNG, JPG, GIF, WebP)
                     * @default File
                     */
                    file: string;
                };
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Avatar image file (PNG, JPG, GIF, WebP)
                     * @default File
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        user: {
                            id: string;
                            username: string;
                            email: string;
                            verified: number;
                            avatarUrl: string | null;
                            role: string;
                            aqi?: number;
                            ppm?: number;
                            firstName?: string;
                            lastName?: string;
                            phoneNumber?: string;
                            age?: number;
                        };
                    };
                };
            };
            /** @description Response for status 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
            /** @description Response for status 500 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
        };
    };
    getApiUserMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        user: {
                            id: string;
                            username: string;
                            email: string;
                            verified: number;
                            avatarUrl: string | null;
                            role: string;
                            aqi?: number;
                            ppm?: number;
                            firstName?: string;
                            lastName?: string;
                            phoneNumber?: string;
                            age?: number;
                        };
                    };
                };
            };
            /** @description Response for status 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
        };
    };
    patchApiUserMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username?: string;
                    email?: string;
                    avatarUrl?: string;
                    firstName?: string;
                    lastName?: string;
                    phoneNumber?: string;
                    age?: number;
                };
                "application/x-www-form-urlencoded": {
                    username?: string;
                    email?: string;
                    avatarUrl?: string;
                    firstName?: string;
                    lastName?: string;
                    phoneNumber?: string;
                    age?: number;
                };
                "multipart/form-data": {
                    username?: string;
                    email?: string;
                    avatarUrl?: string;
                    firstName?: string;
                    lastName?: string;
                    phoneNumber?: string;
                    age?: number;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        user: {
                            id: string;
                            username: string;
                            email: string;
                            verified: number;
                            avatarUrl: string | null;
                            role: string;
                            aqi?: number;
                            ppm?: number;
                            firstName?: string;
                            lastName?: string;
                            phoneNumber?: string;
                            age?: number;
                        };
                    };
                };
            };
            /** @description Response for status 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: string;
                    };
                };
            };
        };
    };
}
